schema_version: 0.2.0
slug: project-2620
project_title: 127 Lincoln Place
client_name: Ingui Architecture
building_name: 127 Lincoln Place
phase: Design Analysis
report_date: '2026-09-22'
prepared_by: bldgtyp, llc
contact_email: john@bldgtyp.com
target_standard: PHI EnerPHit 'by Demand'
certification_program: TBD
certification_path: TBD
recommended_variant_id: ''
certification_pathways:
  show: [enerphit-component, enerphit-demand,phi-classic]
  recommended: enerphit-demand
building:
  address: 127 Lincoln Place
  city: Brooklyn
  state: NY
  climate_zone: 4A
  building_type: Row House
  total_num_occupants: 3.3
source_files:
  phpp_path: ../07_PHPP/2620 127 Lincoln Place.xlsx
  cad_files_received_date: 09/08/2026
  data_dir: data
  assets_dir: public/assets
publishing:
  production_url: https://project-2620.bldgtyp.com
  cloudflare_pages_project: bt-proj-2620-lincoln
  access:
    mode: public
    allowed_emails: []
narrative:
  certification:
    enph_ag_ext_limit: ''
    enph_ag_int_limit: ''
    enph_bg_limit: ''
    enph_hd_limit: ''
    enph_per_limit: ''
    enph_uw_limit: ''
    ph_ach_limit: ''
    phi_lcd_limit: ''
    phius_cd_limit: ''
    phius_cfm50_limit: ''
    phius_cl_limit: ''
    phius_hd_limit: ''
    phius_hl_limit: ''
    phius_nse_limit: ''
    target: ''
  climate:
    ashrae_design_temps: ''
    ashrae_location_name: ''
    ashrae_winter_design_temp_C: ''
    ashrae_winter_design_temp_F: ''
    state_name: ''
    state_name_abbreviation: ''
    weather_station_name: ''
    weather_station_url: ''
  co2:
    epa_subgrid_name: ''
    occupancy: ''
    subregion_name: ''
    taget_co2_per_person: ''
    target_tons: ''
  energy_code:
    ach_limit: '3'
    ach_link: ''
    code_airtightness_url: ''
    code_base_url: ''
    link: ''
    name: ''
    u_val_link: ''
    window_min_u_value: ''
    zone: ''
  mechanical:
    erv:
      link: ''
      manufacturer_name: ''
      type_name: ''
  windows:
    comfort_target_r_value: ''
    comfort_target_u_value: ''
    ph_window_r_value: ''
    ph_window_u_value: ''
